config/routes.rb
WordProblemAnswererRails::Application.routes.draw do
  resources :word_problems

  

end

app/models/word_problem.rb
class WordProblem < ActiveRecord::Base

  validates_presence_of :problem
  validates_presence_of :solution

  validates_numericality_of :solution

  validate :problem_is_valid

  def solve
    if solver.valid?
      self.solution = solver.solution
      if valid?
        self.save
      end
    else
      problem_is_valid
      false
    end
  end

  protected

  def problem_is_valid
    if !solver.valid?
      errors.add(:problem, 'is not well formed')
    end
  end

  def solver
    WordProblemSolver.new(self.problem)
  end

end

app/models/word_problem_solver.rb
class WordProblemSolver

  attr_reader :left_side_number, :right_side_number

  def initialize(worded_problem)
    @worded_problem = worded_problem

    if !@worded_problem.nil?
      # The first match is for the entire string and then each of the parens captures each digit separately
      matches = @worded_problem.match(/(\d+) plus (\d+)/)
      if matches.present? && matches.size ==3
        @left_side_number = matches[1].to_i
        @right_side_number = matches[2].to_i
      end
    end
  end

  def valid?
    @left_side_number.present? &&
    @right_side_number.present? &&
    mathematical_operation.present?
  end

  def mathematical_operation
    'plus'
  end

  def solution
    self.left_side_number + self.right_side_number
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/word_problems_controller.rb
class WordProblemsController < ApplicationController

  def new
    @word_problem = WordProblem.new
  end


  def create
    @word_problem = WordProblem.new(word_problem_params)

    respond_to do |format|
      if @word_problem.solve
        format.html { redirect_to @word_problem, notice: 'We solved it for you!' }
        format.json { render action: 'show', status: :created, location: @word_problem }
      else
        format.html { render action: 'new' }
        format.json { render json: @word_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @word_problem = WordProblem.find(params[:id])
  end


  private

  def word_problem_params
      params.require(:word_problem).permit(:problem)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/word_problems_helper.rb
module WordProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordProblemAnswererRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/word_problems/new.html.erb
<h1>Create a new Word Problem</h1>

<%= form_for(@word_problem) do |f| %>
    <% if @word_problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word_problem.errors.count, "error") %> prohibited this registration from being saved:</h2>

      <ul>
      <% @word_problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :problem %><br>
    <%= f.text_area :problem %>
  </div>

  <div class="actions">
    <%= f.submit "Solve" %>
  </div>


<%- end -%>

app/views/word_problems/show.html.erb
<%= notice %>
<br>
<p>You asked:
  <%= @word_problem.problem %>
</p>
<p>The answer is:
  <%= @word_problem.solution %>
</p>
<%= link_to 'Ask another problem', new_word_problem_path %>